### ISSUE TITLE
Raw socket creation

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa-rules#179]
## Summary

Creation of raw sockets.

## Examples

`WSASocketA(2, 3, 0, 0, 0, 1)`

## Features

socket functions
constants, see https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-socket, https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-wsasocketa

**Comment by williballenthin** [comment]
`AF_INET`, `SOCK_RAW`, protocol not specified
