### ISSUE TITLE
capture-webcam-video

### ISSUE THREAD

**Issue by recvfrom** [mandiant/capa-rules#286]
## Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your rule idea isn't already filed: [search](https://github.com/fireeye/capa-rules/issues?q=is%3Aissue+is%3Aopen+)

## Summary

Let's have a rule that detects a system's webcam being used to capture video

## Examples

TBD

## Features

I'd need to look around for real world examples that do this, but it seems like we could look for calling `capCreateCaptureWindow` + calling `capCaptureSequence` + (calling `capFileSaveAs` or calling `capFileSetCaptureFile`)

## Additional context

N/A

### Namespace
collection/webcam

### References
- https://docs.microsoft.com/en-us/windows/win32/multimedia/capturing-data
- https://docs.microsoft.com/en-us/windows/win32/multimedia/naming-the-capture-file

### Other rule meta information

N/A

**Comment by mr-tz** [comment]
Great idea. Would love to see a sample with this functionality.

**Comment by williballenthin** [comment]
https://www.virustotal.com/gui/file/1059f624494514c8366a300d034b57feb9eefed82fe61fb03cb500c8a48eebdc/content/strings

might be a candidate, and could also be used for a `exposes a Java binding` rule. maybe audio capture, too.

![image](https://user-images.githubusercontent.com/156560/109886311-19a49d80-7c3d-11eb-83a1-18cac8c71c7b.png)
