### ISSUE TITLE
nursery/mine-cryptocurrency FPs a lot

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa-rules#292]
the `mine-cryptocurrency` rule FPs a fair amount, because it consists of a single top level OR of many strings, including a bunch of four letter words. we should tighten up this rule, to ensure there are multiple string matches, and the strings are much longer than 4 characters.

**Comment by mr-tz** [comment]
https://github.com/mandiant/capa-rules/pull/713 tweaked (and renamed to `reference cryptocurrency strings`) the rule, please reopen if this is still an issue.
