### ISSUE TITLE
encode data using JSON

### ISSUE THREAD

**Issue by Ana06** [mandiant/capa-rules#326]
## Rule name

`encode data using JSON`

## Summary

Encode data using JavaScript Object Notation (JSON).

## Possible test samples

Publicly available samples that may contain the capability this rule should detect  (MD5 hashes):
- 285e57297f578e565dc814301149edbf
- d32fc81161b5bec6e6fb2326c47b3d3e

## Namespace

Proposed namespace: `data-manipulation/encoding`. More details in https://github.com/fireeye/capa-rules/blob/master/doc/format.md#rule-namespace

## att&ck

`aka.mitre.att&ck.t1027`

**Comment by mr-tz** [comment]
handled in various cases, see https://github.com/search?q=repo%3Amandiant%2Fcapa-rules%20json&type=code
