### ISSUE TITLE
Create and open section

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa-rules#4]
NtCreateSection, ZwCreateSection, NtOpenSection, ZwOpenSection
- https://ired.team/offensive-security/code-injection-process-injection/ntcreatesection-+-ntmapviewofsection-code-injection
- https://www.cyberbit.com/blog/endpoint-security/malware-mitigation-when-direct-system-calls-are-used/

**Comment by johnk3r** [comment]
Please let me help you with that.
