### ISSUE TITLE
FPs encrypt-data-using-rc4-prga.yml

### ISSUE THREAD

**Issue by r0ny123** [mandiant/capa-rules#435]
As discussed here https://github.com/fireeye/capa/pull/679#issuecomment-884306100
Followed by @williballenthin's comment https://github.com/fireeye/capa/pull/679#issuecomment-884332188

**Comment by mr-tz** [comment]
Thanks, for easier reference: `ec1c29cb6674ffce989576c51413a6f9cbb4a8a41cbd30ec628182485a937160:0x10061294` (running capa with the SMDA backend)

**Comment by mr-tz** [comment]
@r0ny123, happy to hear your thoughts on #661

**Comment by r0ny123** [comment]
Thanks @mr-tz for taking a look :) . Im afk now. Will take a look later.
