### ISSUE TITLE
CI: lint --thorough on weekly basis

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa-rules#457]
nice, let's set this up as a recurring check in GitHub Actions?!

_Originally posted by @mr-tz in https://github.com/fireeye/capa-rules/issues/455#issuecomment-908214669_

**Comment by williballenthin** [comment]
this took me 4hrs to run locally - its still pretty heavyweight. i agree about testing regularly, though i'm not sure whats feasible.

**Comment by williballenthin** [comment]
should we reconsider the freeze format again?

**Comment by mr-tz** [comment]
Per https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration that should work?!

> Job execution time - Each job in a workflow can run for up to 6 hours of execution time. If a job reaches this limit, the job is terminated and fails to complete.
> 
> Workflow run time - Each workflow run is limited to 72 hours. If a workflow run reaches this limit, the workflow run is cancelled.
