### ISSUE TITLE
add coverage of bad MAC addresses checked by SharpShooter framework

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa-rules#465]
check performed [here](https://github.com/mdsecactivebreach/SharpShooter/blob/9aea0b7a723b61c01c21f1e4b55409edf39a5a3b/CSharpShooterStageless/CheckPlease.cs#L77).

we might already cover these but let's double-check.

**Comment by mike-hunhoff** [comment]
referenced code is {{.NET}} but checks could also be performed in C/C++, etc.

**Comment by williballenthin** [comment]
i dont think we have any anti-vm checks via mac address yet. at least not that i found with some basic grepping.

**Comment by mike-hunhoff** [comment]
@williballenthin good catch; I thought we did already so this would make for a good starting point 🚀
