### ISSUE TITLE
invalid rule: unexpected statement: instruction

### ISSUE THREAD

**Issue by Azotium** [mandiant/capa-rules#552]
Hello,

Running capa without the rules works correctly. 
But if I add the rule parameter pointing to the capa-rules folder, I get the following error:

`ERROR:capa:invalid rule: capa-rules/data-manipulation/encryption/hc-128/encrypt-data-using-hc-128.yml: invalid rule: unexpected statement: instruction`

**Comment by mr-tz** [comment]
Thanks, we're aware of the issue and plan to avoid the confusion in the future.

Please see issue #551 and especially https://github.com/mandiant/capa-rules/issues/551#issuecomment-1095126994

In the short term, you'll want to download the rules from tag v3.2.0, like here: https://github.com/mandiant/capa-rules/tree/v3.2.0 or use capa master.

**Comment by williballenthin** [comment]
i've reverted the breaking changes in master and the rules now work with capa v3.2.0:

![image](https://user-images.githubusercontent.com/156560/165584435-b755623d-cfc7-4be5-bf01-0226aa89f2e6.png)

i've reverted the reverts in https://github.com/mandiant/capa-rules/tree/v4-dev. we should merge this branch into `master` when we go to release v4. further discussion in #556. updated capa documentation in https://github.com/mandiant/capa/pull/1006

**Comment by williballenthin** [comment]
thanks for reporting the issue @Azotium!
