### ISSUE TITLE
systax error 

### ISSUE THREAD

**Issue by quangnv97** [mandiant/capa-rules#555]
i use capa.exe v3.2.0-0-gd9d72ad, when use with default rule => everything good.
but when i use with rule clone from https://github.com/mandiant/capa-rules => an syntax error occurred

```
ERROR:capa:invalid rule: C:\github\capa-rules\anti-analysis\anti-debugging\debugger-detection\check-for-peb-ntglobalflag-flag.yml: invalid rule: unexpected statement: instruction
```
same issue happen when use in IDA 7.6 Pro sp1

**Comment by williballenthin** [comment]
i've reverted the breaking changes in master and the rules now work with capa v3.2.0:

![image](https://user-images.githubusercontent.com/156560/165584435-b755623d-cfc7-4be5-bf01-0226aa89f2e6.png)

i've reverted the reverts in https://github.com/mandiant/capa-rules/tree/v4-dev. we should merge this branch into `master` when we go to release v4. further discussion in #556. updated capa documentation in https://github.com/mandiant/capa/pull/1006

**Comment by williballenthin** [comment]
thanks for reporting the issue @quangnv97!
