### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by d01a** [mandiant/capa-rules#593]
I faced this error in both IDA and cli capa
ERROR:capa.ida.plugin.form:Failed to load rules from C:/capa-rules-master (error: invalid rule: C:/capa-rules-master\anti-analysis\anti-debugging\debugger-detection\check-for-kernel-debugger-via-shared-user-data-structure.yml: invalid rule: unexpected statement: instruction).
ERROR:capa.ida.plugin.form:Make sure your file directory contains properly formatted capa rules. You can download the standard collection of capa rules from https://github.com/mandiant/capa-rules.
INFO:capa.ida.plugin.form:Analysis failed.

this problem not only in this rule but un many other rules 
capa version: 3.2.1 (using pip)
capa-rules: the katest in the repository
ida version: 7.7

**Comment by TrQ-Hoan** [comment]
Hot fix `git reset --hard bdf76e6e19`

**Comment by mr-tz** [comment]
Please see https://github.com/mandiant/capa/blob/master/doc/rules.md on pointers which rules to use with which version.
Sorry, about the confusion. The v4 release will also "fix" this.
