### ISSUE TITLE
check Anti-DebugNET coverage

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa-rules#595]
https://github.com/Mecanik/Anti-DebugNET

**Comment by williballenthin** [comment]
- anti debug: `System.Diagnostics.Debugger.IsAttached`
  - anti debug: `IsDebuggerPresent()`
  - anti debug: `CheckRemoteDebuggerPresent`, `System.Diagnostics.Process.GetCurrentProcess().Handle`

a bunch of functionality around NtInformationClass that we can't really ID from .NET

**Comment by mr-tz** [comment]
covered files from https://github.com/Mecanik/Anti-DebugNET/tree/master/Anti-DebugNET/AntiDebug in #721
TODO:
- [ ] AntiDebugTools
- [ ] AntiDump
