### ISSUE TITLE
Idea - Malicious Libraries in TRJ_BANKER

### ISSUE THREAD

**Issue by johnk3r** [mandiant/capa-rules#609]
Hi,

what is the best way to create rule/rules to detect these suspicious libraries?

![2022-08-13 20_46_52-Configurações](https://user-images.githubusercontent.com/6247648/184516917-5e977afe-96e9-44e9-b449-1bcccf3695d7.png)

Would it be a rule for each library?

Ref.: https://www.welivesecurity.com/2021/04/06/janeleiro-time-traveler-new-old-banking-trojan-brazil/

**Comment by johnk3r** [comment]
https://twitter.com/johnk3r/status/1558600148309131266

**Comment by mr-tz** [comment]
Yes, one rule per library fits best with our current approach.

Additionally, we could add a parent rule that combines these, however, that's optional and likely doesn't add much value but may require more maintenance.

**Comment by mr-tz** [comment]
Would you mind submitting a PR based on your existing rule(s)?
