### ISSUE TITLE
Stack Strings has its own ID

### ISSUE THREAD

**Issue by utkonos** [mandiant/capa-rules#633]
Should this rule also result in:

```
Anti-Static Analysis::Executable Code Obfuscation::Stack Strings [B0032.017]
```

https://github.com/mandiant/capa-rules/blob/1fee68e72e5da3cf05cbf349d8b4df13dcf47a85/anti-analysis/obfuscation/string/stackstring/contain-obfuscated-stackstrings.yml#L11

**Comment by williballenthin** [comment]
thats great! would you consider opening a PR with this change so we can have you listed as a contributor?

**Comment by williballenthin** [comment]
this rule probably pre-dates the MBC term for stack strings. thanks for catching us up.

**Comment by utkonos** [comment]
Yes, I will definitely make a PR. I want to wait until I get some feedback on this issue/thread/stream of conciousness:

https://github.com/MBCProject/mbc-markdown/issues/63

I think there is a blurry area in the definition of Executable Code Obfuscation vs Disassembler Evasion. Long story short: I understand disassembled evasion to be a behavior that interferes with the disassember itself or the disassembly process resulting in incorrect assembly code, incomplete assembly code, crashed disassember, or halting of disassemby process with an error or a crash. Therefore, I think that "Argument Obfuscation" and "Variable Recomposition" should be moved to Executable Code Obfuscation because they don't fit the definition of Disassembler Evasion.

I will return to making a PR to this rule once I am clear on whether those changes are correct of if I'm totally wrong.

**Comment by williballenthin** [comment]
ah, thanks for the explanation @utkonos. I can certainly follow your line of thinking, so we'll just have to see if the MBC stewards can be swayed.

Incidentally, I'm glad that you're speaking up here to keep the definitions precise; without contributions like this, a project like MBC wouldn't make it far. Thank you!

**Comment by mr-tz** [comment]
Hey @utkonos, looks like the discussion has been addressed. Can you open a PR or can I help with that?

**Comment by utkonos** [comment]
@mr-tz I'm super swamped at the moment. If you want to go ahead, that's fine. It's on my todo list.

**Comment by mr-tz** [comment]
Please see #668.
