### ISSUE TITLE
Create rules releases

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa-rules#642]
Add releases of `capa-rules` to ease usability
- [x] update documentation (doc/rules.md in flare-capa), see https://github.com/mandiant/capa/pull/1245
  - [x] no more git, simply download ZIP
  - [x] capa code master and rules master guaranteed to work together, not necessarily true for other combinations
- [x] create historic rule releases
- [x] automatically generated via GitHub Actions, see #643 
- [x] update code (error outputs, etc.), see https://github.com/mandiant/capa/pull/1247
- [x] remove vX branches
- [x] ~~append to / link to releases in flare-capa~~ (tabling for now)

**Comment by mr-tz** [comment]
@mike-hunhoff and @williballenthin do you agree that we can now remove the vX branches and tags, v1, v2, etc.?

**Comment by williballenthin** [comment]
yup I agreeOn Jan 2, 2023, at 6:38 PM, Moritz ***@***.***> wrote:﻿
@mike-hunhoff and @williballenthin do you agree that we can now remove the vX branches and tags, v1, v2, etc.?

**Comment by mr-tz** [comment]
Branches and tags have been removed.
