### ISSUE TITLE
dotnet: execute using startup hook

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa-rules#646]
https://rastamouse.me/net-startup-hooks/
https://github.com/dotnet/runtime/blob/main/docs/design/features/host-startup-hook.md

**Comment by williballenthin** [comment]
> It’s a .NET DLL that has no namespace, a single class called StartupHook and a method called Initialize.

**Comment by williballenthin** [comment]
simple example of `DOTNET_STARTUP_HOOKS`:

https://www.virustotal.com/gui/file/b12e1ff9ee034426e72c380b4429304acc482724a4a563b28a12350f1738f8cc

`Microsoft.VisualStudio.HotReload.Components.DeltaApplier.ApplyProcessEnvironmentVariablesAsync`
![image](https://user-images.githubusercontent.com/156560/210320255-f49af733-eb93-40c8-8545-a58df22b604e.png)

**Comment by williballenthin** [comment]
simple example of `StartupHook`:

https://www.virustotal.com/gui/file/62824e3ddd0ebf5742cc836f9a205fcdc197bb3dee049d6a376ed68e886c4c05 (via VT search: `entity:file tag:assembly "StartupHook"`)

![image](https://user-images.githubusercontent.com/156560/210321135-ff05d793-c5c9-4097-b942-87480780d3cb.png)

**Comment by williballenthin** [comment]
we need a .NET feature that describes names of classes/functions implemented within the module. for example, given:

![image](https://user-images.githubusercontent.com/156560/210322249-92c552a0-9bd0-4218-9c95-1184b961cb1e.png)

we see right now:

![image](https://user-images.githubusercontent.com/156560/210322297-d1562e17-df9c-4906-866b-3200f2e03c62.png)

but not a feature describing the name `StartupHook.Initialize`
