### ISSUE TITLE
api: inet_pton

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa-rules#678]
inet_pton converts an IPv4 or IPv6 Internet network address in its standard text presentation form into its numeric binary form

https://learn.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-inet_pton

**Comment by williballenthin** [comment]
what namespace would you propose for this? `communication/ip::manipulate IP address` ?

**Comment by mr-tz** [comment]
how about just using `communication/ip`?
