### ISSUE TITLE
combine c2 and communication namespaces

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa-rules#682]
Does it make sense to combine the c2 and communication namespaces so they show up under one common parent?

[c2](https://github.com/mandiant/capa-rules/blob/master/c2) - commands that may be issued by a controller, such as interactive shell or file transfer

[communication](https://github.com/mandiant/capa-rules/blob/master/communication) - HTTP, TCP, etc.

IMO c2 falls under communication.

This is for example relevant when filtering by namespace.

**Comment by williballenthin** [comment]
I think moving c2 under communication makes sense. The c2 commands are essentially another layer of protocol, just like IP or TCP. 

With only two c2 categories I don't think this is a big change that we should over-think.
