### ISSUE TITLE
split at.exe detection into its own rule

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa-rules#693]
i wonder if we should split these rules out so that the techniques don't get mixed (e.g. don't want to tag "AT job" if at wasn't used).

_Originally posted by @williballenthin in https://github.com/mandiant/capa-rules/pull/685#discussion_r1097318511_

**Comment by joren485** [comment]
This is done in #685.

**Comment by mr-tz** [comment]
Thanks!
