### ISSUE TITLE
triage ATT&CK v13

### ISSUE THREAD

**Issue by ghost** [mandiant/capa-rules#752]
https://attack.mitre.org/resources/updates/updates-april-2023/index.html

### New Techniques

- [x] #753 
- [x] #754 
- not obviously relevant:
  - [x] Unsecured Credentials: [Chat Messages](https://attack.mitre.org/techniques/T1552/008) (v1.0)
  - [x] [Acquire Access](https://attack.mitre.org/techniques/T1650) (v1.0)
  - [x] Acquire Infrastructure: [Malvertising](https://attack.mitre.org/techniques/T1583/008) (v1.0)
  - [x] [Cloud Administration Command](https://attack.mitre.org/techniques/T1651) (v1.0)
  - [x] Command and Scripting Interpreter: [Cloud API](https://attack.mitre.org/techniques/T1059/009) (v1.0)
  - [x] Impair Defenses: [Spoof Security Alerting](https://attack.mitre.org/techniques/T1562/011) (v1.0)
  - [x] Masquerading: [Masquerade File Type](https://attack.mitre.org/techniques/T1036/008) (v1.0)
  - [x] Obfuscated Files or Information: [Command Obfuscation](https://attack.mitre.org/techniques/T1027/010) (v1.0)
  - [x] Obfuscated Files or Information: [Fileless Storage](https://attack.mitre.org/techniques/T1027/011) (v1.0)
  - [x] Remote Services: [Cloud Services](https://attack.mitre.org/techniques/T1021/007) (v1.0)
  - [x] Exfiltration Over Web Service: [Exfiltration to Text Storage Sites](https://attack.mitre.org/techniques/T1567/003) (v1.0)

**Comment by mr-tz** [comment]
All handled
