### ISSUE TITLE
rule: capture major, minor, build versions via ntdll (need example)

### ISSUE THREAD

**Issue by Ana06** [mandiant/capa-rules#80]
@mike-hunhoff
> Example: `b7841b9d5dc1f511a93cc7576672ec0c:0x1000f0e0`
> 
> The example above uses `LoadLibrary`/`GetProcAddress` and won't be captured by capa.
> 
> Windows API:
> * `ntdll:RtlGetNtVersionNumbers`

**Comment by mr-tz** [comment]
see #85 and #662
