### ISSUE TITLE
check for unmoving mouse cursor

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa-rules#941]
Using `thread` scope for this rule is too broad, I keep seeing hits for processes like `explorer.exe`. Unfortunately, our current dynamic implementation doesn't support a > `call` and < `thread` scope which is what we really need here to avoid FPs...

**Comment by mr-tz** [comment]
should we disable it for dynamic for now?

**Comment by mike-hunhoff** [comment]
+1 for disabling it for dynamic analysis
