### ISSUE TITLE
Modify ProcessDynamicCodePolicy Value

### ISSUE THREAD

**Issue by Ezbeat** [mandiant/capa-rules#966]
[anti-analysis/anti-av/block-operations-on-executable-memory-pages-using-arbitrary-code-guard.yml](https://github.com/mandiant/capa-rules/blob/e50d824553ae8d7168ac2d1f7b5540a93f944e28/anti-analysis/anti-av/block-operations-on-executable-memory-pages-using-arbitrary-code-guard.yml)

The rule currently uses 8 for `ProcessDynamicCodePolicy`, but the correct value should be 2 according to documentation and observations. 
I kindly request an update to the rule. 

Thank you!

```cpp
typedef enum _PROCESS_MITIGATION_POLICY {
    ProcessDEPPolicy,
    ProcessASLRPolicy,
    ProcessDynamicCodePolicy, // 2
    ProcessStrictHandleCheckPolicy,
    ProcessSystemCallDisablePolicy,
    ProcessMitigationOptionsMask,
    ProcessExtensionPointDisablePolicy,
    ProcessControlFlowGuardPolicy,
    ProcessSignaturePolicy,
    ProcessFontDisablePolicy,
    ProcessImageLoadPolicy,
    ProcessSystemCallFilterPolicy,
    ProcessPayloadRestrictionPolicy,
    ProcessChildProcessPolicy,
    ProcessSideChannelIsolationPolicy,
    ProcessUserShadowStackPolicy,
    ProcessRedirectionTrustPolicy,
    ProcessUserPointerAuthPolicy,
    ProcessSEHOPPolicy,
    MaxProcessMitigationPolicy
} PROCESS_MITIGATION_POLICY, *PPROCESS_MITIGATION_POLICY;
```

**Comment by mr-tz** [comment]
@jtothej can you confirm the proposed update?
